### ISSUE TITLE
Update localforage adapter to latest version

### ISSUE THREAD

**Issue by fwenzel** [brittanystoroz/its-five-o-clock-somewhere#1]
Importing it in the broccoli file is deprecated. The new guide does it better:

https://developer.mozilla.org/en-US/Apps/Build/Modern_web_app_architecture/Models_and_application_data#Storing_data_with_LocalForage

**Comment by brittanydionigi** [comment]
Resolved as of ed2ebf5173a30f72847c13928b62bf67eb8add5e
